ChibiOS/RT: MAC Low Level Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
MAC Low Level Driver
[MAC Driver]
MAC Driver low level driver template.
Description
MAC Driver low level driver template.
This file is a template for a MAC low level driver.
Data Structures
struct MACDriver
Structure representing a MAC driver.
struct MACTransmitDescriptor
Structure representing a transmit descriptor.
struct MACReceiveDescriptor
Structure representing a receive descriptor.
Defines
#define MAC_TRANSMIT_BUFFERS 2
Number of available transmit buffers.
#define MAC_RECEIVE_BUFFERS 2
Number of available receive buffers.
#define MAC_BUFFERS_SIZE 1518
Maximum supported frame size.
Functions
void mac_lld_init (void)
Low level MAC initialization.
void mac_lld_set_address (MACDriver *macp, const uint8_t *p)
Low level MAC address setup.
msg_t max_lld_get_transmit_descriptor (MACDriver *macp, MACTransmitDescriptor *tdp)
Returns a transmission descriptor.
size_t mac_lld_write_transmit_descriptor (MACTransmitDescriptor *tdp, uint8_t *buf, size_t size)
Writes to a transmit descriptor's stream.
void mac_lld_release_transmit_descriptor (MACTransmitDescriptor *tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
msg_t max_lld_get_receive_descriptor (MACDriver *macp, MACReceiveDescriptor *rdp)
Returns a receive descriptor.
size_t mac_lld_read_receive_descriptor (MACReceiveDescriptor *rdp, uint8_t *buf, size_t size)
Reads from a receive descriptor's stream.
void mac_lld_release_receive_descriptor (MACReceiveDescriptor *rdp)
Releases a receive descriptor.
bool_t mac_lld_poll_link_status (MACDriver *macp)
Updates and returns the link status.
Define Documentation
#define MAC_TRANSMIT_BUFFERS 2
Number of available transmit buffers.
Definition at line 52 of file templates/mac_lld.h.
#define MAC_RECEIVE_BUFFERS 2
Number of available receive buffers.
Definition at line 59 of file templates/mac_lld.h.
#define MAC_BUFFERS_SIZE 1518
Maximum supported frame size.
Definition at line 66 of file templates/mac_lld.h.
Function Documentation
void mac_lld_init (void)
Low level MAC initialization.
Referenced by macInit().
void mac_lld_set_address (MACDriver * macp, const uint8_t * p)
Low level MAC address setup.
Parameters:
[in] macp pointer to the MACDriver object
[in] p pointer to a six bytes buffer containing the MAC address. If this parameter is set to NULL then a system default MAC is used.
Referenced by macSetAddress().
msg_t max_lld_get_transmit_descriptor (MACDriver * macp, MACTransmitDescriptor * tdp)
Returns a transmission descriptor.
One of the available transmission descriptors is locked and returned.
Parameters:
[in] macp pointer to the MACDriver object
[out] tdp pointer to a MACTransmitDescriptor structure
Returns:
The operation status.
Return values:
RDY_OK a descriptor was obtained.
RDY_TIMEOUT descriptor not available.
Referenced by macWaitTransmitDescriptor().
size_t mac_lld_write_transmit_descriptor (MACTransmitDescriptor * tdp, uint8_t * buf, size_t size)
Writes to a transmit descriptor's stream.
Parameters:
[in] tdp pointer to a MACTransmitDescriptor structure
[in] buf pointer to the buffer containing the data to be written
[in] size number of bytes to be written
Returns:
The number of bytes written into the descriptor's stream, this value can be less than the amount specified in the parameter size if the maximum frame size is reached.
void mac_lld_release_transmit_descriptor (MACTransmitDescriptor * tdp)
Releases a transmit descriptor and starts the transmission of the enqueued data as a single frame.
Parameters:
[in] tdp pointer to a MACTransmitDescriptor structure
Referenced by macReleaseTransmitDescriptor().
msg_t max_lld_get_receive_descriptor (MACDriver * macp, MACReceiveDescriptor * rdp)
Returns a receive descriptor.
Parameters:
[in] macp pointer to a MACDriver object
[out] rdp pointer to a MACReceiveDescriptor structure
Returns:
The operation status.
Return values:
RDY_OK a descriptor was obtained.
RDY_TIMEOUT descriptor not available.
Referenced by macWaitReceiveDescriptor().
size_t mac_lld_read_receive_descriptor (MACReceiveDescriptor * rdp, uint8_t * buf, size_t size)
Reads from a receive descriptor's stream.
Parameters:
[in] rdp pointer to a MACReceiveDescriptor structure
[in] buf pointer to a buffer that will receive the read data
[in] size number of bytes to be read
Returns:
The number of bytes read from the descriptor's stream, this value can be less than the amount specified in the parameter size if there are no more bytes to read.
void mac_lld_release_receive_descriptor (MACReceiveDescriptor * rdp)
Releases a receive descriptor.
The descriptor and its buffer are made available for more incoming frames.
Parameters:
[in] rdp pointer to a MACReceiveDescriptor structure
Referenced by macReleaseReceiveDescriptor().
bool_t mac_lld_poll_link_status (MACDriver * macp)
Updates and returns the link status.
Parameters:
[in] macp pointer to a MACDriver object
Returns:
The link status.
Return values:
TRUE if the link is active.
FALSE if the link is down.
Referenced by macPollLinkStatus().