ChibiOS/RT: PWM Low Level Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
PWM Low Level Driver
[PWM Driver]
PWM Driver low level driver template.
Description
PWM Driver low level driver template.
Data Structures
struct PWMChannelConfig
PWM driver channel configuration structure.
struct PWMConfig
Driver configuration structure.
struct PWMDriver
Structure representing an PWM driver.
Defines
#define PWM_CHANNELS 1
Number of PWM channels per PWM driver.
#define PWM_FRACTION_TO_WIDTH(pwmp, numerator, denominator) 0
Converts from fraction to pulse width.
#define PWM_DEGREES_TO_WIDTH(pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
#define PWM_PERCENTAGE_TO_WIDTH(pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Typedefs
typedef uint8_t pwmchannel_t
PWM channel type.
typedef uint16_t pwmcnt_t
PWM counter type.
typedef struct PWMDriver PWMDriver
Type of a structure representing an PWM driver.
typedef void(* pwmcallback_t)(PWMDriver *pwmp)
PWM notification callback type.
Functions
void pwm_lld_init (void)
Low level PWM driver initialization.
void pwm_lld_start (PWMDriver *pwmp)
Configures and activates the PWM peripheral.
void pwm_lld_stop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
bool_t pwm_lld_is_enabled (PWMDriver *pwmp, pwmchannel_t channel)
Determines whatever the PWM channel is already enabled.
void pwm_lld_enable_channel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwm_lld_disable_channel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel.
Define Documentation
#define PWM_CHANNELS 1
Number of PWM channels per PWM driver.
Definition at line 52 of file templates/pwm_lld.h.
Referenced by pwmDisableChannel(), and pwmEnableChannel().
#define PWM_FRACTION_TO_WIDTH (pwmp, numerator, denominator) 0
Converts from fraction to pulse width.
Note:
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters:
[in] numerator numerator of the fraction
[in] denominator percentage as an integer between 0 and numerator
Returns:
The pulse width to be passed to pwmEnableChannel().
Definition at line 160 of file templates/pwm_lld.h.
#define PWM_DEGREES_TO_WIDTH (pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
Note:
Be careful with rounding errors, this is integer math not magic. You can specify hundredths of degrees but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] degrees degrees as an integer between 0 and 36000
Returns:
The pulse width to be passed to pwmEnableChannel().
Definition at line 175 of file templates/pwm_lld.h.
#define PWM_PERCENTAGE_TO_WIDTH (pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Note:
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] percentage percentage as an integer between 0 and 10000
Returns:
The pulse width to be passed to pwmEnableChannel().
Definition at line 191 of file templates/pwm_lld.h.
Typedef Documentation
typedef uint8_t pwmchannel_t
PWM channel type.
Definition at line 66 of file templates/pwm_lld.h.
typedef uint16_t pwmcnt_t
PWM counter type.
Definition at line 71 of file templates/pwm_lld.h.
typedef struct PWMDriver PWMDriver
Type of a structure representing an PWM driver.
Definition at line 76 of file templates/pwm_lld.h.
typedef void(* pwmcallback_t)(PWMDriver *pwmp)
PWM notification callback type.
Parameters:
[in] pwmp pointer to a PWMDriver object
Definition at line 83 of file templates/pwm_lld.h.
Function Documentation
void pwm_lld_init (void)
Low level PWM driver initialization.
Referenced by pwmInit().
void pwm_lld_start (PWMDriver * pwmp)
Configures and activates the PWM peripheral.
Parameters:
[in] pwmp pointer to the PWMDriver object
Referenced by pwmStart().
void pwm_lld_stop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters:
[in] pwmp pointer to the PWMDriver object
Referenced by pwmStop().
bool_t pwm_lld_is_enabled (PWMDriver * pwmp, pwmchannel_t channel)
Determines whatever the PWM channel is already enabled.
Parameters:
[in] pwmp pointer to the PWMDriver object
[in] channel PWM channel identifier
Returns:
The PWM channel status.
Return values:
FALSE the channel is not enabled.
TRUE the channel is enabled.
void pwm_lld_enable_channel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
[in] width PWM pulse width as clock pulses number
Referenced by pwmEnableChannel().
void pwm_lld_disable_channel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel.
The channel is disabled and its output line returned to the idle state.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Referenced by pwmDisableChannel().