ChibiOS/RT: STM32 PWM Support
ChibiOS/RT
Architecture - Reference Manual - Guides
STM32 PWM Support
[STM32 Support]
TIMx peripherals as PWM generators support.
Description
TIMx peripherals as PWM generators support.
The PWM driver supports the STM32 TIMx units as PWM generators.
Functions
void pwm_lld_init (void)
Low level PWM driver initialization.
void pwm_lld_start (PWMDriver *pwmp)
Configures and activates the PWM peripheral.
void pwm_lld_stop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
void pwm_lld_enable_channel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwm_lld_disable_channel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel.
Variables
PWMDriver PWMD1
PWM1 driver identifier.
PWMDriver PWMD2
PWM2 driver identifier.
PWMDriver PWMD3
PWM3 driver identifier.
PWMDriver PWMD4
PWM4 driver identifier.
Function Documentation
void pwm_lld_init (void)
Low level PWM driver initialization.
Definition at line 206 of file platforms/STM32/pwm_lld.c.
References PWMDriver::pd_enabled_channels, PWMDriver::pd_tim, and pwmObjectInit().
void pwm_lld_start (PWMDriver * pwmp)
Configures and activates the PWM peripheral.
Parameters:
[in] pwmp pointer to a PWMDriver object
Definition at line 258 of file platforms/STM32/pwm_lld.c.
References CORTEX_PRIORITY_MASK, NVICEnableVector(), PWMConfig::pc_arr, PWMConfig::pc_callback, PWMConfig::pc_channels, PWMConfig::pc_cr2, PWMConfig::pc_psc, PWMChannelConfig::pcc_mode, PWMDriver::pd_config, PWMDriver::pd_enabled_channels, PWMDriver::pd_state, PWMDriver::pd_tim, PWM_OUTPUT_ACTIVE_HIGH, PWM_OUTPUT_ACTIVE_LOW, PWM_STOP, STM32_PWM1_IRQ_PRIORITY, STM32_PWM2_IRQ_PRIORITY, STM32_PWM3_IRQ_PRIORITY, and STM32_PWM4_IRQ_PRIORITY.
void pwm_lld_stop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters:
[in] pwmp pointer to a PWMDriver object
Definition at line 370 of file platforms/STM32/pwm_lld.c.
References NVICDisableVector(), PWMDriver::pd_enabled_channels, PWMDriver::pd_state, PWMDriver::pd_tim, and PWM_READY.
void pwm_lld_enable_channel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
[in] width PWM pulse width as clock pulses number
Definition at line 421 of file platforms/STM32/pwm_lld.c.
References PWMConfig::pc_channels, PWMChannelConfig::pcc_callback, PWMDriver::pd_config, PWMDriver::pd_enabled_channels, and PWMDriver::pd_tim.
void pwm_lld_disable_channel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel.
The channel is disabled and its output line returned to the idle state.
Parameters:
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Definition at line 446 of file platforms/STM32/pwm_lld.c.
References PWMDriver::pd_enabled_channels, and PWMDriver::pd_tim.
Variable Documentation
PWMDriver PWMD1
PWM1 driver identifier.
Note:
The driver PWM1 allocates the complex timer TIM1 when enabled.
Definition at line 49 of file platforms/STM32/pwm_lld.c.
PWMDriver PWMD2
PWM2 driver identifier.
Note:
The driver PWM2 allocates the timer TIM2 when enabled.
Definition at line 57 of file platforms/STM32/pwm_lld.c.
PWMDriver PWMD3
PWM3 driver identifier.
Note:
The driver PWM3 allocates the timer TIM3 when enabled.
Definition at line 65 of file platforms/STM32/pwm_lld.c.
PWMDriver PWMD4
PWM4 driver identifier.
Note:
The driver PWM4 allocates the timer TIM4 when enabled.
Definition at line 73 of file platforms/STM32/pwm_lld.c.