ChibiOS/RT: chibios_rt::Semaphore Class Reference
ChibiOS/RT
Architecture - Reference Manual - Guides
chibios_rt::Semaphore Class Reference
Class encapsulating a semaphore.
#include <ch.hpp>
Public Member Functions
Semaphore (cnt_t n)
Semaphore constructor.
void Reset (cnt_t n)
Resets a semaphore.
msg_t Wait (void)
Wait operation on the semaphore.
msg_t WaitTimeout (systime_t time)
Wait operation on the semaphore with timeout.
void Signal (void)
Signal operation on the semaphore.
Static Public Member Functions
static msg_t SignalWait (Semaphore *ssem, Semaphore *wsem)
Atomic signal and wait operations.
Data Fields
struct::Semaphore sem
Embedded Semaphore structure.
Detailed Description
Class encapsulating a semaphore.
Definition at line 295 of file ch.hpp.
Constructor & Destructor Documentation
Semaphore::Semaphore (cnt_t n)
Semaphore constructor.
The embedded Semaphore structure is initialized.
Parameters:
n the semaphore counter value, must be greater or equal to zero
Definition at line 168 of file ch.cpp.
References chSemInit(), and sem.
Member Function Documentation
void Semaphore::Reset (cnt_t n)
Resets a semaphore.
Parameters:
n the new semaphore counter value, must be greater or equal to zero
Definition at line 173 of file ch.cpp.
References chSemReset(), and sem.
msg_t Semaphore::Wait (void)
Wait operation on the semaphore.
Return values:
RDY_OK if the semaphore was signaled or not taken.
RDY_RESET if the semaphore was reset.
Definition at line 178 of file ch.cpp.
References chSemWait(), and sem.
msg_t Semaphore::WaitTimeout (systime_t time)
Wait operation on the semaphore with timeout.
Parameters:
time the number of ticks before the operation fails
Return values:
RDY_OK if the semaphore was signaled or not taken.
RDY_RESET if the semaphore was reset.
RDY_TIMEOUT if the semaphore was not signaled or reset within the specified timeout.
Definition at line 183 of file ch.cpp.
References chSemWaitTimeout(), and sem.
void Semaphore::Signal (void)
Signal operation on the semaphore.
The semaphore is signaled, the next thread in queue, if any, is awakened.
Definition at line 188 of file ch.cpp.
References chSemSignal(), and sem.
msg_t Semaphore::SignalWait (Semaphore * ssem, Semaphore * wsem) [static]
Atomic signal and wait operations.
Parameters:
ssem pointer to a Semaphore to be signaled
wsem pointer to a Semaphore to be wait on
Return values:
RDY_OK if the semaphore was signaled or not taken.
RDY_RESET if the semaphore was reset.
Definition at line 194 of file ch.cpp.
References chSemSignalWait(), and sem.
Field Documentation
struct ::Semaphore chibios_rt::Semaphore::sem
Embedded Semaphore structure.
Definition at line 300 of file ch.hpp.
Referenced by Reset(), Semaphore(), Signal(), SignalWait(), Wait(), and WaitTimeout().