ChibiOS/RT: SPI Low Level Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
SPI Low Level Driver
[SPI Driver]
SPI Driver low level driver template.
Description
SPI Driver low level driver template.
This file is a template for a SPI low level driver.
Data Structures
struct SPIConfig
Driver configuration structure.
struct SPIDriver
Structure representing a SPI driver.
Functions
void spi_lld_init (void)
Low level SPI driver initialization.
void spi_lld_start (SPIDriver *spip)
Configures and activates the SPI peripheral.
void spi_lld_stop (SPIDriver *spip)
Deactivates the SPI peripheral.
void spi_lld_select (SPIDriver *spip)
Asserts the slave select signal and prepares for transfers.
void spi_lld_unselect (SPIDriver *spip)
Deasserts the slave select signal.
void spi_lld_ignore (SPIDriver *spip, size_t n)
Ignores data on the SPI bus.
void spi_lld_exchange (SPIDriver *spip, size_t n, const void *txbuf, void *rxbuf)
Exchanges data on the SPI bus.
void spi_lld_send (SPIDriver *spip, size_t n, const void *txbuf)
Sends data ever the SPI bus.
void spi_lld_receive (SPIDriver *spip, size_t n, void *rxbuf)
Receives data from the SPI bus.
Function Documentation
void spi_lld_init (void)
Low level SPI driver initialization.
Referenced by spiInit().
void spi_lld_start (SPIDriver * spip)
Configures and activates the SPI peripheral.
Parameters:
[in] spip pointer to the SPIDriver object
Referenced by spiStart().
void spi_lld_stop (SPIDriver * spip)
Deactivates the SPI peripheral.
Parameters:
[in] spip pointer to the SPIDriver object
Referenced by spiStop().
void spi_lld_select (SPIDriver * spip)
Asserts the slave select signal and prepares for transfers.
Parameters:
[in] spip pointer to the SPIDriver object
Referenced by spiSelect().
void spi_lld_unselect (SPIDriver * spip)
Deasserts the slave select signal.
The previously selected peripheral is unselected.
Parameters:
[in] spip pointer to the SPIDriver object
Referenced by spiUnselect().
void spi_lld_ignore (SPIDriver * spip, size_t n)
Ignores data on the SPI bus.
This function transmits a series of idle words on the SPI bus and ignores the received data. This function can be invoked even when a slave select signal has not been yet asserted.
Parameters:
[in] spip pointer to the SPIDriver object
[in] n number of words to be ignored
Referenced by spiIgnore().
void spi_lld_exchange (SPIDriver * spip, size_t n, const void * txbuf, void * rxbuf)
Exchanges data on the SPI bus.
This function performs a simultaneous transmit/receive operation.
Note:
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters:
[in] spip pointer to the SPIDriver object
[in] n number of words to be exchanged
[in] txbuf the pointer to the transmit buffer
[out] rxbuf the pointer to the receive buffer
Referenced by spiExchange().
void spi_lld_send (SPIDriver * spip, size_t n, const void * txbuf)
Sends data ever the SPI bus.
Note:
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters:
[in] spip pointer to the SPIDriver object
[in] n number of words to send
[in] txbuf the pointer to the transmit buffer
Referenced by spiSend().
void spi_lld_receive (SPIDriver * spip, size_t n, void * rxbuf)
Receives data from the SPI bus.
Note:
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters:
[in] spip pointer to the SPIDriver object
[in] n number of words to receive
[out] rxbuf the pointer to the receive buffer
Referenced by spiReceive().