ChibiOS/RT: ARMv7-M Specific Implementation
ChibiOS/RT
Architecture - Reference Manual - Guides
ARMv7-M Specific Implementation
[Core Port Implementation]
ARMv7-M specific port code, structures and macros.
Description
ARMv7-M specific port code, structures and macros.
Defines
#define SETUP_CONTEXT(workspace, wsize, pf, arg)
Platform dependent part of the chThdInit() API.
#define IDLE_THREAD_STACK_SIZE 8
Stack size for the system idle thread.
#define INT_REQUIRED_STACK 16
Per-thread stack overhead for interrupts servicing.
#define PORT_IRQ_PROLOGUE()
IRQ prologue code.
#define PORT_IRQ_EPILOGUE() _port_irq_epilogue()
IRQ epilogue code.
#define PORT_IRQ_HANDLER(id) void id(void)
IRQ handler function declaration.
#define PORT_FAST_IRQ_HANDLER(id) void id(void)
Fast IRQ handler function declaration.
#define port_init()
Port-related initialization code.
#define port_lock()
Kernel-lock action.
#define port_unlock()
Kernel-unlock action.
#define port_lock_from_isr() port_lock()
Kernel-lock action from an interrupt handler.
#define port_unlock_from_isr() port_unlock()
Kernel-unlock action from an interrupt handler.
#define port_disable() asm volatile ("cpsid i" : : : "memory")
Disables all the interrupt sources.
#define port_suspend()
Disables the interrupt sources below kernel-level priority.
#define port_enable()
Enables all the interrupt sources.
#define port_wait_for_interrupt()
Enters an architecture-dependent IRQ-waiting mode.
Functions
CH_IRQ_HANDLER (SysTickVector)
System Timer vector.
void SVCallVector (void)
SVC vector.
void _port_irq_epilogue (void)
Reschedule verification and setup after an IRQ.
void _port_switch_from_isr (void)
Post-IRQ switch code.
void port_switch (Thread *ntp, Thread *otp)
Performs a context switch between two threads.
void _port_thread_start (void)
Start a thread by invoking its work function.
void port_halt (void)
Halts the system.
Define Documentation
#define SETUP_CONTEXT (workspace, wsize, pf, arg)
Value:
{                          \
  tp->p_ctx.r13 = (struct intctx *)((uint8_t *)workspace +                  \
                                     wsize -                                \
                                     sizeof(struct intctx));                \
  tp->p_ctx.r13->r4 = pf;                                                   \
  tp->p_ctx.r13->r5 = arg;                                                  \
  tp->p_ctx.r13->lr = _port_thread_start;                                   \
}
Platform dependent part of the chThdInit() API.
This code usually setup the context switching frame represented by an intctx structure.
Definition at line 87 of file chcore_v7m.h.
#define IDLE_THREAD_STACK_SIZE 8
Stack size for the system idle thread.
This size depends on the idle thread implementation, usually the idle thread should take no more space than those reserved by INT_REQUIRED_STACK.
Note:
In this port it is set to 8 because the idle thread does have a stack frame when compiling without optimizations. You may reduce this value to zero when compiling with optimizations.
Definition at line 106 of file chcore_v7m.h.
#define INT_REQUIRED_STACK 16
Per-thread stack overhead for interrupts servicing.
This constant is used in the calculation of the correct working area size. This value can be zero on those architecture where there is a separate interrupt stack and the stack space between intctx and extctx is known to be zero.
Note:
In this port it is conservatively set to 16 because the function chSchDoRescheduleI() can have a stack frame, expecially with compiler optimizations disabled.
Definition at line 121 of file chcore_v7m.h.
#define PORT_IRQ_PROLOGUE ()
IRQ prologue code.
This macro must be inserted at the start of all IRQ handlers enabled to invoke system APIs.
Definition at line 129 of file chcore_v7m.h.
#define PORT_IRQ_EPILOGUE () _port_irq_epilogue()
IRQ epilogue code.
This macro must be inserted at the end of all IRQ handlers enabled to invoke system APIs.
Definition at line 136 of file chcore_v7m.h.
#define PORT_IRQ_HANDLER (id) void id(void)
IRQ handler function declaration.
Note:
id can be a function name or a vector number depending on the port implementation.
Definition at line 143 of file chcore_v7m.h.
#define PORT_FAST_IRQ_HANDLER (id) void id(void)
Fast IRQ handler function declaration.
Note:
id can be a function name or a vector number depending on the port implementation.
Definition at line 150 of file chcore_v7m.h.
#define port_init (void)
Value:
{                                                       \
  SCB_AIRCR = AIRCR_VECTKEY | AIRCR_PRIGROUP(0);                            \
  NVICSetSystemHandlerPriority(HANDLER_SVCALL,                              \
    CORTEX_PRIORITY_MASK(CORTEX_PRIORITY_SVCALL));                          \
  NVICSetSystemHandlerPriority(HANDLER_SYSTICK,                             \
    CORTEX_PRIORITY_MASK(CORTEX_PRIORITY_SYSTICK));                         \
}
Port-related initialization code.
Definition at line 155 of file chcore_v7m.h.
#define port_lock (void)
Value:
{                                                       \
  asm volatile ("bl      _port_lock" : : : "r3", "lr", "memory");           \
}
Kernel-lock action.
Usually this function just disables interrupts but may perform more actions.
Note:
In this port this it raises the base priority to kernel level.
Definition at line 175 of file chcore_v7m.h.
#define port_unlock (void)
Value:
{                                                     \
  asm volatile ("bl      _port_unlock" : : : "r3", "lr", "memory");         \
}
Kernel-unlock action.
Usually this function just disables interrupts but may perform more actions.
Note:
In this port this it lowers the base priority to user level.
Definition at line 192 of file chcore_v7m.h.
#define port_lock_from_isr (void) port_lock()
Kernel-lock action from an interrupt handler.
This function is invoked before invoking I-class APIs from interrupt handlers. The implementation is architecture dependent, in its simplest form it is void.
Note:
Same as port_lock() in this port.
Definition at line 204 of file chcore_v7m.h.
#define port_unlock_from_isr (void) port_unlock()
Kernel-unlock action from an interrupt handler.
This function is invoked after invoking I-class APIs from interrupt handlers. The implementation is architecture dependent, in its simplest form it is void.
Note:
Same as port_unlock() in this port.
Definition at line 213 of file chcore_v7m.h.
#define port_disable (void) asm volatile ("cpsid i" : : : "memory")
Disables all the interrupt sources.
Note:
Of course non maskable interrupt sources are not included.
In this port it disables all the interrupt sources by raising the priority mask to level 0.
Definition at line 221 of file chcore_v7m.h.
#define port_suspend (void)
Value:
{                                                    \
  register uint32_t tmp asm ("r3") = CORTEX_BASEPRI_KERNEL;                 \
  asm volatile ("msr     BASEPRI, %0                    \n\t"               \
                "cpsie   i" : : "r" (tmp) : "memory");                      \
}
Disables the interrupt sources below kernel-level priority.
Note:
Interrupt sources above kernel level remains enabled.
In this port it raises/lowers the base priority to kernel level.
Definition at line 228 of file chcore_v7m.h.
#define port_enable (void)
Value:
{                                                     \
  register uint32_t tmp asm ("r3") = CORTEX_BASEPRI_DISABLED;               \
  asm volatile ("msr     BASEPRI, %0                    \n\t"               \
                "cpsie   i" : : "r" (tmp) : "memory");                      \
}
Enables all the interrupt sources.
Note:
In this port it lowers the base priority to user level.
Definition at line 238 of file chcore_v7m.h.
#define port_wait_for_interrupt (void)
Value:
{                                         \
  asm volatile ("wfi" : : : "memory");                                      \
}
Enters an architecture-dependent IRQ-waiting mode.
The function is meant to return when an interrupt becomes pending. The simplest implementation is an empty function or macro but this would not take advantage of architecture-specific power saving modes.
Note:
Implemented as an inlined WFI instruction.
Definition at line 253 of file chcore_v7m.h.
Function Documentation
CH_IRQ_HANDLER (SysTickVector)
System Timer vector.
This interrupt is used as system tick.
Note:
The timer must be initialized in the startup code.
Definition at line 82 of file chcore_v7m.c.
References CH_IRQ_EPILOGUE, CH_IRQ_PROLOGUE, chSysLockFromIsr, chSysTimerHandlerI(), and chSysUnlockFromIsr.
void SVCallVector (void)
SVC vector.
The SVC vector is used for exception mode re-entering after a context switch.
Definition at line 98 of file chcore_v7m.c.
References port_unlock_from_isr().
void _port_irq_epilogue (void)
Reschedule verification and setup after an IRQ.
void _port_switch_from_isr (void)
Post-IRQ switch code.
Exception handlers return here for context switching.
void port_switch (Thread * ntp, Thread * otp)
Performs a context switch between two threads.
This is the most critical code in any port, this function is responsible for the context switch between 2 threads.
Note:
The implementation of this code affects directly the context switch performance so optimize here as much as you can.
Parameters:
[in] ntp the thread to be switched in
[in] otp the thread to be switched out
void _port_thread_start (void)
Start a thread by invoking its work function.
If the work function returns chThdExit() is automatically invoked.
void port_halt (void)
Halts the system.
This function is invoked by the operating system when an unrecoverable error is detected (as example because a programming error in the application code that triggers an assertion while in debug mode).
This function is invoked by the operating system when an unrecoverable error is detected (as example because a programming error in the application code that triggers an assertion while in debug mode).
Note:
The function is declared as a weak symbol, it is possible to redefine it in your application code.
The function is declared as a weak symbol, it is possible to redefine it in your application code.
Definition at line 45 of file ports/GCC/ARMCMx/chcore.c.
References port_disable().