ChibiOS/RT: Serial Low Level Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
Serial Low Level Driver
[Serial Driver]
Serial Driver low level driver template.
Description
Serial Driver low level driver template.
This file is a template for a serial low level driver.
Data Structures
struct SerialConfig
Generic Serial Driver configuration structure.
Defines
#define _serial_driver_data
SerialDriver specific data.
Typedefs
typedef uint8_t sdflags_t
Serial Driver condition flags type.
Functions
void sd_lld_init (void)
Low level serial driver initialization.
void sd_lld_start (SerialDriver *sdp, const SerialConfig *config)
Low level serial driver configuration and (re)start.
void sd_lld_stop (SerialDriver *sdp)
Low level serial driver stop.
Define Documentation
#define _serial_driver_data
Value:
_base_asynchronous_channel_data                                           \
  /* Driver state.*/                                                        \
  sdstate_t                 state;                                          \
  /* Input queue.*/                                                         \
  InputQueue                iqueue;                                         \
  /* Output queue.*/                                                        \
  OutputQueue               oqueue;                                         \
  /* Status Change @p EventSource.*/                                        \
  EventSource               sevent;                                         \
  /* I/O driver status flags.*/                                             \
  sdflags_t                 flags;                                          \
  /* Input circular buffer.*/                                               \
  uint8_t                   ib[SERIAL_BUFFERS_SIZE];                        \
  /* Output circular buffer.*/                                              \
  uint8_t                   ob[SERIAL_BUFFERS_SIZE];                        \
SerialDriver specific data.
Definition at line 76 of file templates/serial_lld.h.
Typedef Documentation
typedef uint8_t sdflags_t
Serial Driver condition flags type.
Definition at line 59 of file templates/serial_lld.h.
Function Documentation
void sd_lld_init (void)
Low level serial driver initialization.
Referenced by sdInit().
void sd_lld_start (SerialDriver * sdp, const SerialConfig * config)
Low level serial driver configuration and (re)start.
Parameters:
[in] sdp pointer to a SerialDriver object
[in] config the architecture-dependent serial driver configuration. If this parameter is set to NULL then a default configuration is used.
Referenced by sdStart().
void sd_lld_stop (SerialDriver * sdp)
Low level serial driver stop.
De-initializes the USART, stops the associated clock, resets the interrupt vector.
Parameters:
[in] sdp pointer to a SerialDriver object
Referenced by sdStop().