ChibiOS/RT: Serial Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
Serial Driver
[HAL]
Generic Serial Driver.
Description
Generic Serial Driver.
This module implements a generic full duplex serial driver. The driver implements a SerialDriver interface and uses I/O Queues for communication between the upper and the lower driver. Event flags are used to notify the application about incoming data, outgoing data and other I/O events.
The module also contains functions that make the implementation of the interrupt service routines much easier.
Data Structures
struct SerialDriverVMT
SerialDriver virtual methods table.
struct _SerialDriver
Full duplex serial driver class.
Modules
Serial Low Level Driver
Serial Driver low level driver template.
Defines
#define SD_NO_ERROR 0
No pending conditions.
#define SD_CONNECTED 1
Connection happened.
#define SD_DISCONNECTED 2
Disconnection happened.
#define SD_PARITY_ERROR 4
Parity error happened.
#define SD_FRAMING_ERROR 8
Framing error happened.
#define SD_OVERRUN_ERROR 16
Overflow happened.
#define SD_NOISE_ERROR 32
Noise on the line.
#define SD_BREAK_DETECTED 64
Break detected.
#define SERIAL_DEFAULT_BITRATE 38400
Default bit rate.
#define SERIAL_BUFFERS_SIZE 64
Serial buffers size.
#define _serial_driver_methods _base_asynchronous_channel_methods
SerialDriver specific methods.
#define sdPutWouldBlock(sdp) chOQIsFull(&(sdp)->oqueue)
Direct output check on a SerialDriver.
#define sdGetWouldBlock(sdp) chIQIsEmpty(&(sdp)->iqueue)
Direct input check on a SerialDriver.
#define sdPut(sdp, b) chOQPut(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
#define sdPutTimeout(sdp, b, t) chOQPutTimeout(&(sdp)->iqueue, b, t)
Direct write to a SerialDriver with timeout specification.
#define sdGet(sdp) chIQGet(&(sdp)->iqueue)
Direct read from a SerialDriver.
#define sdGetTimeout(sdp, t) chIQGetTimeout(&(sdp)->iqueue, t)
Direct read from a SerialDriver with timeout specification.
#define sdWrite(sdp, b, n) chOQWriteTimeout(&(sdp)->oqueue, b, n, TIME_INFINITE)
Direct blocking write to a SerialDriver.
#define sdWriteTimeout(sdp, b, n, t) chOQWriteTimeout(&(sdp)->oqueue, b, n, t)
Direct blocking write to a SerialDriver with timeout specification.
#define sdAsynchronousWrite(sdp, b, n) chOQWriteTimeout(&(sdp)->oqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking write to a SerialDriver.
#define sdRead(sdp, b, n) chIQReadTimeout(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
#define sdReadTimeout(sdp, b, n, t) chIQReadTimeout(&(sdp)->iqueue, b, n, t)
Direct blocking read from a SerialDriver with timeout specification.
#define sdAsynchronousRead(sdp, b, n) chIQReadTimeout(&(sdp)->iqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking read from a SerialDriver.
#define sdGetStatusChangeEventSource(ip) (&((ip)->vmt->sevent))
Returns the status change event source.
Typedefs
typedef struct _SerialDriver SerialDriver
Structure representing a serial driver.
Enumerations
enum sdstate_t { SD_UNINIT = 0, SD_STOP = 1, SD_READY = 2 }
Driver state machine possible states.
Functions
void sdInit (void)
Serial Driver initialization.
void sdObjectInit (SerialDriver *sdp, qnotify_t inotify, qnotify_t onotify)
Initializes a generic full duplex driver object.
void sdStart (SerialDriver *sdp, const SerialConfig *config)
Configures and starts the driver.
void sdStop (SerialDriver *sdp)
Stops the driver.
void sdIncomingDataI (SerialDriver *sdp, uint8_t b)
Handles incoming data.
msg_t sdRequestDataI (SerialDriver *sdp)
Handles outgoing data.
void sdAddFlagsI (SerialDriver *sdp, sdflags_t mask)
Handles communication events/errors.
sdflags_t sdGetAndClearFlags (SerialDriver *sdp)
Returns and clears the errors mask associated to the driver.
Define Documentation
#define SD_NO_ERROR 0
No pending conditions.
Definition at line 45 of file serial.h.
#define SD_CONNECTED 1
Connection happened.
Definition at line 47 of file serial.h.
#define SD_DISCONNECTED 2
Disconnection happened.
Definition at line 49 of file serial.h.
#define SD_PARITY_ERROR 4
Parity error happened.
Definition at line 51 of file serial.h.
#define SD_FRAMING_ERROR 8
Framing error happened.
Definition at line 53 of file serial.h.
#define SD_OVERRUN_ERROR 16
Overflow happened.
Definition at line 55 of file serial.h.
Referenced by sdIncomingDataI().
#define SD_NOISE_ERROR 32
Noise on the line.
Definition at line 57 of file serial.h.
#define SD_BREAK_DETECTED 64
Break detected.
Definition at line 59 of file serial.h.
#define SERIAL_DEFAULT_BITRATE 38400
Default bit rate.
Configuration parameter, this is the baud rate selected for the default configuration.
Definition at line 71 of file serial.h.
#define SERIAL_BUFFERS_SIZE 64
Serial buffers size.
Configuration parameter, you can change the depth of the queue buffers depending on the requirements of your application.
Note:
The default is 64 bytes for both the transmission and receive buffers.
Definition at line 82 of file serial.h.
Referenced by sdObjectInit().
#define _serial_driver_methods _base_asynchronous_channel_methods
SerialDriver specific methods.
Definition at line 116 of file serial.h.
#define sdPutWouldBlock (sdp) chOQIsFull(&(sdp)->oqueue)
Direct output check on a SerialDriver.
This function bypasses the indirect access to the channel and checks directly the output queue. This is faster but cannot be used to check different channels implementations.
See also:
chIOPutWouldBlock()
Definition at line 151 of file serial.h.
#define sdGetWouldBlock (sdp) chIQIsEmpty(&(sdp)->iqueue)
Direct input check on a SerialDriver.
This function bypasses the indirect access to the channel and checks directly the input queue. This is faster but cannot be used to check different channels implementations.
See also:
chIOGetWouldBlock()
Definition at line 161 of file serial.h.
#define sdPut (sdp, b) chOQPut(&(sdp)->oqueue, b)
Direct write to a SerialDriver.
This function bypasses the indirect access to the channel and writes directly on the output queue. This is faster but cannot be used to write to different channels implementations.
See also:
chIOPut()
Definition at line 171 of file serial.h.
#define sdPutTimeout (sdp, b, t) chOQPutTimeout(&(sdp)->iqueue, b, t)
Direct write to a SerialDriver with timeout specification.
This function bypasses the indirect access to the channel and writes directly on the output queue. This is faster but cannot be used to write to different channels implementations.
See also:
chIOPutTimeout()
Definition at line 181 of file serial.h.
#define sdGet (sdp) chIQGet(&(sdp)->iqueue)
Direct read from a SerialDriver.
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
See also:
chIOGet()
Definition at line 191 of file serial.h.
#define sdGetTimeout (sdp, t) chIQGetTimeout(&(sdp)->iqueue, t)
Direct read from a SerialDriver with timeout specification.
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
See also:
chIOGetTimeout()
Definition at line 201 of file serial.h.
#define sdWrite (sdp, b, n) chOQWriteTimeout(&(sdp)->oqueue, b, n, TIME_INFINITE)
Direct blocking write to a SerialDriver.
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write from different channels implementations.
See also:
chIOWriteTimeout()
Definition at line 211 of file serial.h.
#define sdWriteTimeout (sdp, b, n, t) chOQWriteTimeout(&(sdp)->oqueue, b, n, t)
Direct blocking write to a SerialDriver with timeout specification.
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write from different channels implementations.
See also:
chIOWriteTimeout()
Definition at line 223 of file serial.h.
#define sdAsynchronousWrite (sdp, b, n) chOQWriteTimeout(&(sdp)->oqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking write to a SerialDriver.
This function bypasses the indirect access to the channel and writes directly to the output queue. This is faster but cannot be used to write from different channels implementations.
See also:
chIOWriteTimeout()
Definition at line 234 of file serial.h.
#define sdRead (sdp, b, n) chIQReadTimeout(&(sdp)->iqueue, b, n, TIME_INFINITE)
Direct blocking read from a SerialDriver.
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
See also:
chIOReadTimeout()
Definition at line 245 of file serial.h.
#define sdReadTimeout (sdp, b, n, t) chIQReadTimeout(&(sdp)->iqueue, b, n, t)
Direct blocking read from a SerialDriver with timeout specification.
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
See also:
chIOReadTimeout()
Definition at line 257 of file serial.h.
#define sdAsynchronousRead (sdp, b, n) chIQReadTimeout(&(sdp)->iqueue, b, n, TIME_IMMEDIATE)
Direct non-blocking read from a SerialDriver.
This function bypasses the indirect access to the channel and reads directly from the input queue. This is faster but cannot be used to read from different channels implementations.
See also:
chIOReadTimeout()
Definition at line 268 of file serial.h.
#define sdGetStatusChangeEventSource (ip) (&((ip)->vmt->sevent))
Returns the status change event source.
The status change event source is broadcasted when the channel status is updated, the status flags can then be fetched and cheared by using sdGetAndClearFlags().
Parameters:
[in] ip pointer to a SerialDriver object
Returns:
A pointer to an EventSource object.
Definition at line 280 of file serial.h.
Typedef Documentation
typedef struct _SerialDriver SerialDriver
Structure representing a serial driver.
Definition at line 109 of file serial.h.
Enumeration Type Documentation
enum sdstate_t
Driver state machine possible states.
Enumerator:
SD_UNINIT
Not initialized.
SD_STOP
Stopped.
SD_READY
Ready.
Definition at line 100 of file serial.h.
Function Documentation
void sdInit (void)
Serial Driver initialization.
Definition at line 110 of file serial.c.
References sd_lld_init().
Referenced by halInit().
void sdObjectInit (SerialDriver * sdp, qnotify_t inotify, qnotify_t onotify)
Initializes a generic full duplex driver object.
The HW dependent part of the initialization has to be performed outside, usually in the hardware initialization code.
Parameters:
[out] sdp pointer to a SerialDriver structure
[in] inotify pointer to a callback function that is invoked when some data is read from the Queue. The value can be NULL.
[in] onotify pointer to a callback function that is invoked when some data is written in the Queue. The value can be NULL.
Definition at line 128 of file serial.c.
References chEvtInit, chIQInit(), chOQInit(), SERIAL_BUFFERS_SIZE, and _SerialDriver::vmt.
void sdStart (SerialDriver * sdp, const SerialConfig * config)
Configures and starts the driver.
Parameters:
[in] sdp pointer to a SerialDriver object
[in] config the architecture-dependent serial driver configuration. If this parameter is set to NULL then a default configuration is used.
Definition at line 148 of file serial.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, sd_lld_start(), SD_READY, and SD_STOP.
void sdStop (SerialDriver * sdp)
Stops the driver.
Any thread waiting on the driver's queues will be awakened with the message Q_RESET.
Parameters:
[in] sdp pointer to a SerialDrive object
Definition at line 168 of file serial.c.
References chDbgAssert, chDbgCheck, chIQResetI(), chOQResetI(), chSchRescheduleS(), chSysLock, chSysUnlock, sd_lld_stop(), SD_READY, and SD_STOP.
void sdIncomingDataI (SerialDriver * sdp, uint8_t b)
Handles incoming data.
This function must be called from the input interrupt service routine in order to enqueue incoming data and generate the related events.
Note:
The incoming data event is only generated when the input queue becomes non-empty.
In order to gain some performance it is suggested to not use this function directly but copy this code directly into the interrupt service routine.
Parameters:
[in] sdp pointer to a SerialDriver structure
[in] b the byte to be written in the driver's Input Queue
Definition at line 198 of file serial.c.
References chDbgCheck, chEvtBroadcastI(), chIQIsEmpty, chIQPutI(), Q_OK, SD_OVERRUN_ERROR, and sdAddFlagsI().
msg_t sdRequestDataI (SerialDriver * sdp)
Handles outgoing data.
Must be called from the output interrupt service routine in order to get the next byte to be transmitted.
Note:
In order to gain some performance it is suggested to not use this function directly but copy this code directly into the interrupt service routine.
Parameters:
[in] sdp pointer to a SerialDriver structure
Returns:
The byte value read from the driver's output queue.
Return values:
Q_EMPTY if the queue is empty (the lower driver usually disables the interrupt source when this happens).
Definition at line 221 of file serial.c.
References chDbgCheck, chEvtBroadcastI(), chOQGetI(), and Q_OK.
void sdAddFlagsI (SerialDriver * sdp, sdflags_t mask)
Handles communication events/errors.
Must be called from the I/O interrupt service routine in order to notify I/O conditions as errors, signals change etc.
Parameters:
[in] sdp pointer to a SerialDriver structure
[in] mask condition flags to be added to the mask
Definition at line 240 of file serial.c.
References chDbgCheck, and chEvtBroadcastI().
Referenced by sdIncomingDataI().
sdflags_t sdGetAndClearFlags (SerialDriver * sdp)
Returns and clears the errors mask associated to the driver.
Parameters:
[in] sdp pointer to a SerialDriver structure
Returns:
The condition flags modified since last time this function was invoked.
Definition at line 255 of file serial.c.
References chDbgCheck, chSysLock, and chSysUnlock.