ChibiOS/RT: HAL Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
HAL Driver
[HAL]
Hardware Abstraction Layer.
Description
Hardware Abstraction Layer.
The HAL driver performs the system initialization and includes the platform support code shared by the other drivers.
Modules
HAL Low Level Driver
HAL Driver low level driver template.
Configuration
HAL Driver Configuration.
Functions
void halInit (void)
HAL initialization.
Function Documentation
void halInit (void)
HAL initialization.
Definition at line 57 of file hal.c.
References adcInit(), canInit(), hal_lld_init(), macInit(), mmcInit(), pal_default_config, palInit, pwmInit(), sdInit(), and spiInit().