#! /bin/sh

arm-none-eabi-gcc -S -mcpu=cortex-m3 -O0 -ggdb -fomit-frame-pointer \
    -falign-functions=16 -ffunction-sections \
    -Wall -Wextra -Wstrict-prototypes -Wa,-alms=gpg-data.lst \
    -DCORTEX_USE_BASEPRI=TRUE  -DTHUMB_PRESENT -mno-thumb-interwork \
    -DTHUMB_NO_INTERWORKING -mthumb -DTHUMB \
    -I . -I../STM32_USB-FS-Device_Driver/inc -I../USBCDC \
    -I../ChibiOS_2.0.2/os/ports/GCC/ARMCMx \
    -I../ChibiOS_2.0.2/os/ports/GCC/ARMCMx/STM32F10x \
    -I../ChibiOS_2.0.2/os/ports/GCC/ARMCMx/cmsis \
    -I../ChibiOS_2.0.2/os/kernel/include -I../ChibiOS_2.0.2/test \
    -I../ChibiOS_2.0.2/os/hal/include \
    -I../ChibiOS_2.0.2/os/hal/platforms/STM32 -I../boards/OLIMEX_STM32_H103 \
    -I../ChibiOS_2.0.2/os/various gpg-data.c
