ChibiOS/RT: chibios_rt::BaseThread Class Reference
ChibiOS/RT
Architecture - Reference Manual - Guides
chibios_rt::BaseThread Class Reference
Base class for a ChibiOS/RT thread.
#include <ch.hpp>
Inherited by chibios_rt::EnhancedThread< N >.
Public Member Functions
BaseThread (void *workspace, size_t wsize, tprio_t prio)
Thread constructor.
msg_t Wait (void)
Synchronization on Thread exit.
void Resume (void)
Resumes the thread.
void Terminate (void)
Requests thread termination.
msg_t SendMessage (msg_t msg)
Sends a message to the thread and returns the answer.
virtual msg_t Main (void)
Thread body function.
Static Public Member Functions
static void Exit (msg_t msg)
Thread exit.
static void SetPriority (tprio_t newprio)
Changes the thread priority.
static void Sleep (systime_t n)
Suspends the thread execution for the specified number of system ticks.
static void SleepUntil (systime_t time)
Suspends the thread execution until the specified time arrives.
static msg_t SendMessage (::Thread *tp, msg_t msg)
Sends a message to the thread and returns the answer.
static msg_t WaitMessage (void)
Waits for a message and returns it.
static msg_t GetMessage (void)
Returns an enqueued message or NULL.
static void ReleaseMessage (msg_t msg)
Releases the next message in queue with a reply.
static bool IsPendingMessage (void)
Returns true if there is at least one message in queue.
Data Fields
::Thread * thread_ref
Pointer to the system thread.
Detailed Description
Base class for a ChibiOS/RT thread.
The thread body is the virtual function Main().
Definition at line 120 of file ch.hpp.
Constructor & Destructor Documentation
chibios_rt::BaseThread::BaseThread (void * workspace, size_t wsize, tprio_t prio)
Thread constructor.
The thread object is initialized and a system thread is started.
Parameters:
workspace pointer to the workspace area
wsize size of the workspace area
prio thread priority
Definition at line 85 of file ch.cpp.
References chThdCreateStatic(), and thread_ref.
Member Function Documentation
void chibios_rt::BaseThread::Exit (msg_t msg) [static]
Thread exit.
Parameters:
msg the exit message
Definition at line 90 of file ch.cpp.
References chThdExit().
msg_t chibios_rt::BaseThread::Wait (void)
Synchronization on Thread exit.
Returns:
the exit message from the thread
Definition at line 96 of file ch.cpp.
References chThdWait(), and thread_ref.
void chibios_rt::BaseThread::Resume (void)
Resumes the thread.
The thread encapsulated into the object is resumed.
Definition at line 107 of file ch.cpp.
References chThdResume(), and thread_ref.
void chibios_rt::BaseThread::SetPriority (tprio_t newprio) [static]
Changes the thread priority.
Parameters:
newprio the new priority level
Definition at line 102 of file ch.cpp.
References chThdSetPriority().
void chibios_rt::BaseThread::Terminate (void)
Requests thread termination.
A termination flag is pended on the thread, it is thread responsibility to detect it and exit.
Definition at line 112 of file ch.cpp.
References chThdTerminate(), and thread_ref.
void chibios_rt::BaseThread::Sleep (systime_t n) [static]
Suspends the thread execution for the specified number of system ticks.
Parameters:
n the number of system ticks
Definition at line 117 of file ch.cpp.
References chThdSleep().
void chibios_rt::BaseThread::SleepUntil (systime_t time) [static]
Suspends the thread execution until the specified time arrives.
Parameters:
time the system time
Definition at line 122 of file ch.cpp.
References chThdSleepUntil().
msg_t chibios_rt::BaseThread::SendMessage (::Thread * tp, msg_t msg) [static]
Sends a message to the thread and returns the answer.
Parameters:
tp the target thread
msg the sent message
Returns:
The returned message.
Definition at line 128 of file ch.cpp.
References chMsgSend().
msg_t chibios_rt::BaseThread::SendMessage (msg_t msg)
Sends a message to the thread and returns the answer.
Parameters:
msg the sent message
Returns:
The returned message.
Definition at line 133 of file ch.cpp.
References chMsgSend(), and thread_ref.
msg_t chibios_rt::BaseThread::WaitMessage (void) [static]
Waits for a message and returns it.
Returns:
The incoming message.
Definition at line 138 of file ch.cpp.
References chMsgWait().
msg_t chibios_rt::BaseThread::GetMessage (void) [static]
Returns an enqueued message or NULL.
Returns:
The incoming message.
Return values:
NULL No incoming message.
Definition at line 143 of file ch.cpp.
References chMsgGet().
void chibios_rt::BaseThread::ReleaseMessage (msg_t msg) [static]
Releases the next message in queue with a reply.
Parameters:
msg the answer message
Definition at line 148 of file ch.cpp.
References chMsgRelease().
bool chibios_rt::BaseThread::IsPendingMessage (void) [static]
Returns true if there is at least one message in queue.
Return values:
TRUE A message is waiting in queue.
FALSE A message is not waiting in queue.
Definition at line 153 of file ch.cpp.
References chMsgIsPendingI, and currp.
msg_t chibios_rt::BaseThread::Main (void) [virtual]
Thread body function.
Returns:
The exit message.
Definition at line 159 of file ch.cpp.
Field Documentation
::Thread* chibios_rt::BaseThread::thread_ref
Pointer to the system thread.
Definition at line 125 of file ch.hpp.
Referenced by BaseThread(), Resume(), SendMessage(), Terminate(), and Wait().