ChibiOS/RT: chibios_rt::CondVar Class Reference
ChibiOS/RT
Architecture - Reference Manual - Guides
chibios_rt::CondVar Class Reference
Class encapsulating a conditional variable.
#include <ch.hpp>
Public Member Functions
CondVar (void)
CondVar constructor.
void Signal (void)
Signals the CondVar.
void Broadcast (void)
Broadcasts the CondVar.
msg_t Wait (void)
Waits on the CondVar while releasing the controlling mutex.
msg_t WaitTimeout (systime_t time)
Waits on the CondVar while releasing the controlling mutex.
Data Fields
struct::CondVar condvar
Embedded CondVar structure.
Detailed Description
Class encapsulating a conditional variable.
Definition at line 410 of file ch.hpp.
Constructor & Destructor Documentation
CondVar::CondVar (void)
CondVar constructor.
The embedded CondVar structure is initialized.
Definition at line 234 of file ch.cpp.
References chCondInit(), and condvar.
Member Function Documentation
void CondVar::Signal (void)
Signals the CondVar.
The next thread waiting on the CondVar, if any, is awakened.
Definition at line 239 of file ch.cpp.
References chCondSignal(), and condvar.
void CondVar::Broadcast (void)
Broadcasts the CondVar.
All the threads waiting on the CondVar, if any, are awakened.
Definition at line 244 of file ch.cpp.
References chCondBroadcast(), and condvar.
msg_t CondVar::Wait (void)
Waits on the CondVar while releasing the controlling mutex.
Returns:
The wakep mode.
Return values:
RDY_OK if the condvar was signaled using chCondSignal().
RDY_RESET if the condvar was signaled using chCondBroadcast().
Definition at line 249 of file ch.cpp.
References chCondWait(), and condvar.
msg_t CondVar::WaitTimeout (systime_t time)
Waits on the CondVar while releasing the controlling mutex.
Parameters:
time the number of ticks before the operation fails
Returns:
The wakep mode.
Return values:
RDY_OK if the condvar was signaled using chCondSignal().
RDY_RESET if the condvar was signaled using chCondBroadcast().
RDY_TIMEOUT if the condvar was not signaled within the specified timeout.
Definition at line 255 of file ch.cpp.
References chCondWaitTimeout(), and condvar.
Field Documentation
struct ::CondVar chibios_rt::CondVar::condvar
Embedded CondVar structure.
Definition at line 415 of file ch.hpp.
Referenced by Broadcast(), CondVar(), Signal(), Wait(), and WaitTimeout().