ChibiOS/RT: ADC Low Level Driver
ChibiOS/RT
Architecture - Reference Manual - Guides
ADC Low Level Driver
[ADC Driver]
ADC Driver low level driver template.
Description
ADC Driver low level driver template.
This file is a template for a ADC low level driver.
Data Structures
struct ADCConversionGroup
Conversion group configuration structure.
struct ADCConfig
Driver configuration structure.
struct ADCDriver
Structure representing an ADC driver.
Typedefs
typedef uint16_t adcsample_t
ADC sample data type.
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
typedef void(* adccallback_t)(adcsample_t *buffer, size_t n)
ADC notification callback type.
Functions
void adc_lld_init (void)
Low level ADC driver initialization.
void adc_lld_start (ADCDriver *adcp)
Configures and activates the ADC peripheral.
void adc_lld_stop (ADCDriver *adcp)
Deactivates the ADC peripheral.
void adc_lld_start_conversion (ADCDriver *adcp)
Starts an ADC conversion.
void adc_lld_stop_conversion (ADCDriver *adcp)
Stops an ongoing conversion.
Typedef Documentation
typedef uint16_t adcsample_t
ADC sample data type.
Definition at line 63 of file templates/adc_lld.h.
typedef uint16_t adc_channels_num_t
Channels number in a conversion group.
Definition at line 68 of file templates/adc_lld.h.
typedef void(* adccallback_t)(adcsample_t *buffer, size_t n)
ADC notification callback type.
Parameters:
[in] buffer pointer to the most recent samples data
[in] n number of buffer rows available starting from buffer
Definition at line 76 of file templates/adc_lld.h.
Function Documentation
void adc_lld_init (void)
Low level ADC driver initialization.
Referenced by adcInit().
void adc_lld_start (ADCDriver * adcp)
Configures and activates the ADC peripheral.
Parameters:
[in] adcp pointer to the ADCDriver object
Referenced by adcStart().
void adc_lld_stop (ADCDriver * adcp)
Deactivates the ADC peripheral.
Parameters:
[in] adcp pointer to the ADCDriver object
Referenced by adcStop().
void adc_lld_start_conversion (ADCDriver * adcp)
Starts an ADC conversion.
Parameters:
[in] adcp pointer to the ADCDriver object
Referenced by adcStartConversion().
void adc_lld_stop_conversion (ADCDriver * adcp)
Stops an ongoing conversion.
Parameters:
[in] adcp pointer to the ADCDriver object
Referenced by adcStopConversion(), and CH_IRQ_HANDLER().